### ISSUE TITLE
Hi, very nice work! Could you give an example to run the simulator? 

### ISSUE THREAD

**Issue by maingoctrung** [kamalheidary/OCT-Simulation#1]

**Comment by kamalheidary** [comment]
Hi, Thanks a lot for your comment and Sorry for the late reply.
You need to download all of the codes and just run OCTsignal.m

There are some default values inside that code. but you can change the values here (Lines 20 and 21):

_Ni = [1 1.5] ; %refractive indexes of our sample
Di = [200]*1e-6; % lengths of  our sample_


Ni and Di, are 2 arrays. Here I applied the thickness of a layer of 200 micrometers with an index number of 1. (I did it because I just did not want to put the sample in the zero path difference, so it is an imaginary layer and the simulator can not sense it, but if you want, you can change it.) after that, there is a semi-infinity layer with an index number of 1.5

If you want to simulate 2 layers sample, you can change these lines like that:

Ni = [1 1.5 1.3] ; %refractive indexes of our sample
Di = [200 150]*1e-6; % lengths of  our sample

Here I added a thickness (150 micrometers) for the initial layer and  I add a semi-infinite layer with an index number of 1.3 after it.

You can add as many layers as you want in the same way.

if you find an error, maybe you can change the resolution of your spectrometer, here ( line 15):

d_lambda = 0.2e-9;    %delta lambda

**Comment by maingoctrung** [comment]
Thanks a lot! I am able to run the experiment now! Really nice work.
